use_frameworks!

target 'SCObjectStorage_Example' do
  pod 'SCObjectStorage', :path => '../'

  target 'SCObjectStorage_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
